config/routes.rb
Rails.application.routes.draw do

  resources :followings

  resources :favoritings

  resources :comments

  get 'my_photos' => 'photos#my_photos', :as => 'my_photos'
  get 'my_favorites' => 'photos#my_favorites', :as => 'my_favorites'
  get 'my_timeline' => 'photos#my_timeline', :as => 'my_timeline'

  resources :photos

  devise_for :users

  root "photos#index"

  resources :users, :only => [:show]

end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :leader, :class_name => "User"

  validates :follower, :presence => true, :uniqueness => { :scope => :leader }

  validates :leader, :presence => true
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  before_action :authorize_user, :only => [:show, :edit, :update, :destroy]

  def authorize_user
    unless current_user == @following.follower || current_user.admin?
      redirect_to root_url, :alert => "Not authorized for that."
    end
  end

  # GET /followings
  # GET /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show
  end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(following_params)
    @following.follower = current_user

    respond_to do |format|
      if @following.save
        format.html { redirect_to :back, notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:follower_id, :leader_id)
    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @following.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h4>

      <ul>
      <% @following.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :follower, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :follower, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :leader, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :leader, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/followings/edit.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @following, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing following</h1>
</div>

<%= render 'form' %>

app/views/followings/index.html.erb
<div class="page-header">
  <%= link_to new_following_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Following
  <% end %>
  <h1>Listing followings</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Follower</th>
            <th>Leader</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @followings) do |following| %>
            <td><%= following.follower.email %></td>
            <td><%= following.leader.email %></td>
            <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/followings/new.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New following</h1>
</div>

<%= render 'form' %>

app/views/followings/show.html.erb
<div class="page-header">
  <%= link_to followings_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_following_path(@following), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show following</h1>
</div>

<dl class="dl-horizontal">
  <dt>Follower:</dt>
  <dd><%= @following.follower %></dd>

  <dt>Leader:</dt>
  <dd><%= @following.leader %></dd>

</dl>