config/routes.rb
Rails.application.routes.draw do

  resources :followings

  resources :favoritings

  resources :comments

  get 'my_photos' => 'photos#my_photos', :as => 'my_photos'
  get 'my_favorites' => 'photos#my_favorites', :as => 'my_favorites'
  get 'my_timeline' => 'photos#my_timeline', :as => 'my_timeline'

  resources :photos

  devise_for :users

  root "photos#index"

  resources :users, :only => [:show]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  default_scope { order("created_at DESC") }

  belongs_to :owner, :class_name => "User"

  mount_uploader :image, ImageUploader

  has_many :comments

  has_many :favoritings

  validates :owner, :presence => true

  validates :image, :presence => true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  before_action :authorize_user, :only => [:edit, :update, :destroy]

  def authorize_user
    unless current_user == @photo.owner || current_user.admin?
      redirect_to root_url, :alert => "Not authorized for that."
    end
  end

  def my_timeline
    @photos = current_user.timeline
  end

  def my_photos
    @photos = current_user.owned_photos
  end

  def my_favorites
    @photos = current_user.favorite_photos.order("favoritings_count DESC")
  end


  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.page(params[:page])
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.owner = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    @photo.owner = current_user

    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:caption, :owner_id, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @photo.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h4>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :caption, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :caption, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-2">
    <div class="media">
      <div class="media-left">
        <%= render 'users/avatar', :user => photo.owner %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= photo.owner.email %></h4>
        <%= time_ago_in_words(photo.created_at) %> ago
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to image_tag(photo.image, :class => "img-responsive"), photo %>
        <p class="lead">
          <%= photo.caption %>
        </p>
        <p>Favorites: <%= photo.favoritings_count %></p>
        <div class="btn-group btn-group-justified" role="group">
          <% favoriting = Favoriting.find_by({ :favorited_by_id => current_user.id, :photo_id => photo.id }) %>
          <% if favoriting.present? %>
            <%= link_to "Unfavorite", favoriting, :method => "delete", :class => "btn btn-default" %>
          <% else %>
            <%= link_to "Favorite", favoritings_url(:favoriting => { :photo_id => photo.id }), :method => "post", :class => "btn btn-default" %>
          <% end %>

          <% if current_user == photo.owner %>
            <%= link_to "Edit", edit_photo_url(photo), :class => "btn btn-default" %>
            <%= link_to "Delete", photo, :method => "delete", :class => "btn btn-default", :data => { :confirm => "Are you sure?" } %>
          <% end %>
        </div>
        <ul class="media-list">
          <%= render photo.comments %>

          <li class="list-group-item">
            <%= form_for Comment.new(:photo_id => photo.id) do |f| %>
              <%= f.hidden_field :photo_id %>
              <%= f.text_field :content, :class => "form-control", :placeholder => "Add a comment" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="page-header">
  <%= link_to photos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @photo, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing photo</h1>
</div>

<%= render 'form' %>

app/views/photos/index.html.erb
<div class="page-header">
  <%= link_to new_photo_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Photo
  <% end %>
  <h1>Listing photos</h1>
</div>

<%= render @photos %>

<div class="row">
  <div class="col-sm-12 text-center">
    <%= paginate @photos %>
  </div>
</div>

app/views/photos/my_favorites.html.erb
<div class="page-header">
  <h1>My Favorites</h1>
</div>

<%= render @photos %>

app/views/photos/my_photos.html.erb
<div class="page-header">
  <h1>My Photos</h1>
</div>

<%= render @photos %>

app/views/photos/my_timeline.html.erb
<div class="page-header">
  <h1>Timeline</h1>
</div>

<%= render @photos %>

app/views/photos/new.html.erb
<div class="page-header">
  <%= link_to photos_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New photo</h1>
</div>

<%= render 'form' %>

app/views/photos/show.html.erb
<%= render @photo %>