config/routes.rb
Rails.application.routes.draw do

  resources :followings

  resources :favoritings

  resources :comments

  get 'my_photos' => 'photos#my_photos', :as => 'my_photos'
  get 'my_favorites' => 'photos#my_favorites', :as => 'my_favorites'
  get 'my_timeline' => 'photos#my_timeline', :as => 'my_timeline'

  resources :photos

  devise_for :users

  root "photos#index"

  resources :users, :only => [:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Photogram</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Photogram", root_url, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "All photos", photos_url %></li>
          <li><%= link_to "My photos", my_photos_url %></li>
          <li><%= link_to "Favorite Photos", my_favorites_url %></li>
          <li><%= link_to "Timeline", my_timeline_url %></li>
          <li class="divider"></li>
          <li><%= link_to "Favoritings", favoritings_url %></li>
          <li><%= link_to "Comments", comments_url %></li>
          <li><%= link_to "Followings", followings_url %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method =>"delete" %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>